## Ontologies and controlled vocabulary

Ontologies provide definitions of terms by defining their relation to other terms in a human interpretable way and thereby create a semantic model of the concepts that are used within a specific research domain. In simpler words, ontologies define terms and set them in relation to one another. With these references you can ensure that terms in your data are always interpreted the same way and it is clear for other users what each term means. This is especially useful for filling in Darwin Core terms like **measurementType** or **measurementMethod** (see chapter [Terms of class Measurement or fact](#mof)).
Next to ontologies, you can also refer to terms listed in a thesaurus, which can be seen as a domain specific dictionary. In contrast to ontologies, searching for a specific term across different thesauri is a bit more cumbersome, as there are no look-up servers where you can directly query several thesauri at once. For filling in the keywords of your [metadata](#metadata) a thesaurus can however be quite helpful and is recommended to use, so we want to list a few thesauri tailored to biodiversity or ecological data:

- [GEMET](https://www.eionet.europa.eu/gemet/en/themes/) - GEneral Multilingual Environmental Thesaurus

- [EnvThes](https://vocabs.lter-europe.net/envthes/en/) - Thesaurus for long term ecological research, monitoring and experiments

- [UNESCO Thesaurus](https://vocabularies.unesco.org/browser/thesaurus/en/)

### Tools to help you

- The [Ontology Lookup Service](http://ebi.ac.uk/ols4/) (OLS) is a repository for biomedical ontologies but it also holds plenty of terms and ontologies relevant for ecology. You can search across ontologies for specific terms or filter for certain ontologies. There is also an [API](#API) available to facilitate the use of OLS in workflows/programs.

- [Ontobee](http://ontobee.org) is a linked data server and another option to browse through around 260 different ontologies and directly search for specific terms. 

- If you are more interested in finding an ontology dedicated to a specific domain, looking directly at the [OBO foundry](http://obofoundry.org/) can be helpful. The OBO Foundry (Open Biological and Biomedical Ontology Foundry) is tailored to biological sciences and develops and maintains ontologies. It is not searchable for individual terms but provides information on each ontology. 

- If you chose a specific ontology and before using it you want to assess how [FAIR](#FAIR) this ontology is, you can use [FOOPS!](https://foops.linkeddata.es/FAIR_validator.html#). It is considered a ontology pitfall scanner for FAIR and by providing the [URI](#URI) of an ontology it assesses how well the ontology matches the FAIR principles. 

## Biological taxonomies
There is a diversity of biological taxonomies that you can use to query taxonomic information for the taxa occurring in your dataset. In this guide we cannot cover all of them but we want to provide some more information on a selected set of taxonomies. 

### GBIF Backbone taxonomy
The [GBIF backbone taxonomy](https://doi.org/10.15468/39omei), as the name indicates, builds the basis of the indexing of the species occurrence records stored at [GBIF](#GBIF) and aims to cover all the species that GBIF deals with. It further aims to bring all different taxa names together and organise them. Taxa are assembled from a hierarchical list of 105 sources, using the Catalogue of Life (COL) as a starting point and thereby tightly linking these two taxonomies. Species not found in the COL are then assembled from the remaining sources that are checked afterwards, making the GBIF backbone taxonomy relatively wide-ranging. 

### Catalogue of Life (COL)
The [Catalogue of Life](https://www.catalogueoflife.org/) is an international community for listing species and aims to create a consistent and up-to-date list of currently accepted species across all known taxonomic groups, which is freely accessible. Besides listing taxa, it aims to show all scientific names a taxon is referenced by. 

### Encyclopedia of Life (EOL)
The [Encyclopedia of Life](https://www.eol.org/) aims to gather knowledge about life on earth and make it globally, openly and freely accessible to everyone. Besides taxonomic information it also provides details on food webs and other ecological aspects of taxa. The community behind it consists of open access biodiversity knowledge providers, such as museums, libraries and universities. 

### Integrated Taxonomic Information System (ITIS)
[ITIS](https://www.itis.gov/) is an authoritative system that contains information about taxa and their relationships. It provides a comprehensive and openly available taxonomy and is used as the taxonomic backbone for the Encyclopedia of Life and within the Catalogue of Life. It aims to provide a comprehensive taxonomy of species worldwide to allow sharing of biodiversity data. 

### World Registry of Marine Species (WoRMS)
[WoRMS](https://www.marinespecies.org/) is authoritative classification and catalogue for marine taxa managed by taxonomists and thematic experts that includes accepted and synonym taxonomic information which allows interpretation of the taxonomic literature. It is the recommended biological taxonomy to retrieve information from when publishing data to OBIS.

### Tools to help you 
If you want to retrieve taxonomic information directly from one of the aforementioned taxonomies, there is a helpful R package available that effectively uses the [APIs](#API) of each of these taxonomies, which is called `taxize` (@R-taxize). With taxize you can do plenty of different operations, for example, directly parsing in a list of taxa and retrieving their taxonomic classification or their identifiers from one of the taxonomies (e.g., `get_gbifid_()` retrieves the taxon information from the GBIF backbone taxonomy). If you want to check whether the species names you use in your data are up to date, if they are spelled correctly or if you only have common names but not scientific names in your data, you can use the global name resolving function of taxize (`gnr_resolve()`). The Global Names Resolver is a service provided by the EOL and shows you which names could be matched to your input name and in which taxonomies or data sources they can be found. 

If you query your taxonomic information from a taxonomy you should however always check manually, whether the taxa are identified correctly. Not all taxa are present in all taxonomies or names between taxa are so similar that they are confused for the same taxon in the name matching process.

## Creating GUIDs {#GUIDcreation}

A globally unique identifier (GUID) is a text string of 36 characters that can be used, amongst others, to assign unique identifiers to each data record. It was established as a variation of the Universally Unique Identifier (UUID) but now both are used synonymously. In contrast to other [persistent identifiers (PID)](#PID) that are assigned to the data level, such as DOI, GUIDs do not have to be issued by a central authority but can be created individually by using a generation algorithm/generator. There are different types of GUID, for more information see [here](https://www.techtarget.com/searchwindowsserver/definition/GUID-global-unique-identifier). 

A GUID is build as follows:

> {XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX} 

where each X is a hexadecimal digit, meaning a number from 0 to 9 or a letter from A to F. Through its structure it is extremely unlikely that one GUID is repeated, making it globally unique. 

To assign GUIDs to your data you can:

- use an online GUID generator, for example https://www.uuidgenerator.net

- use the R package `uuid`(@R-uuid) and its function `UUIDgenerate()`

<div>