# (PART\*) __________________________________ {.unnumbered}

# How to reach full interoperability {#fully-interoperable}

As mentioned [before](#evaluation) (see note box), you cannot reach the full score in the evaluation of your data by going through this guide alone. This is because we do not cover the implementation of the [FAIR principle **I1**](https://www.go-fair.org/fair-principles/i1-metadata-use-formal-accessible-shared-broadly-applicable-language-knowledge-representation/): *(Meta)data use a formal, accessible, shared, and broadly applicable language for knowledge representation*. We think that data scientists rather than ecologists are better equipped at using, for example, [RDF](#RDF) (Resource description framework) or [OWL](#OWL) (Web ontology language) for knowledge representation and transforming the data accordingly. 

If you are however interested in making your data fully FAIR and cover principle I1, the following resources can be a good starting point:

-   [Open data support - Training Module 1.3: Introduction to RDF & SPARQL](https://data.europa.eu/sites/default/files/d2.1.2_training_module_1.3_introduction_to_rdf_sparql_en_edp.pdf)

-   [Darwin Core RDF guide](https://dwc.tdwg.org/rdf/)

-   [Cambridge semantics - Semantics university: Learn RDF](https://cambridgesemantics.com/blog/semantic-university/learn-rdf/)

-   [W3C Web Ontology Language guide](https://www.w3.org/TR/owl-guide/)
